name: helping_hands_supported_living
description: "At Helping Hands Supported Living, we specialize in assisting homeless individuals, including ex-offenders, settled asylum seekers, and refugees, to reintegrate into the community."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dynamic_path_url_strategy: ^1.0.0
  easy_url_launcher: ^0.0.7
  flexible_grid_view: ^0.0.2
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_awesome_buttons: ^1.1.0
  flutter_carousel_widget: ^3.1.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/images/
    - lib/assets/images/whatweare/
